###get all
GET http://localhost:3006/contacts


###get by Id
GET http://localhost:3006/contacts/bb395ae7-e2d8-4caa-bb48-418003a4fe6d

###insert a new contact
POST http://localhost:3006/contacts
Content-Type: application/json

{
  "id": "bb395ae7-e2d8-3caa-bb58-418002a4fe6e",
  "name": "jane",
  "email": "jane@gmail.com"
}

###update a contact
PUT http://localhost:3006/contacts/bb395ae7-e2d8-3caa-bb58-418002a4fe6e/
Content-Type: application/json

{
  "name": "jane II",
  "email": "janeii@gmail.com"
}

### Delete a contact
DELETE http://localhost:3006/contacts/bb395ae7-e2d8-3caa-bb58-418002a4fe6e/

